<?php
/**
 * FunAdmin
 * ============================================================================
 * 版权所有 2017-2028 FunAdmin，并保留所有权利。
 * 网站地址: https://www.FunAdmin.com
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp8实现
 * ============================================================================
 * Author: yuege
 * Date: 2017/8/2
 */
namespace app\backend\controller;
use app\backend\middleware\SystemLog;
use app\backend\middleware\ViewNode;
use app\backend\service\AuthService;
use app\common\controller\Backend;
use Exception;
use fun\helper\SignHelper;
use http\Header;
use think\App;

class Login extends Backend {


    protected array $noNeedLogin = ['index','verify'];

    protected $layout='';

    public function __construct(App $app) {
        parent::__construct($app);
        if(config('funadmin.standalone') && request()->baseFile()=='/index.php'){
            header("Location: /");
            exit();
        }
    }
    public function index(){
        $redirect = $this->normalizeRedirect((string) $this->request->param('redirect', ''));
        if (!$this->request->isPost()) {
            $admin= session('admin');
            if ($admin) {
                $this->redirect($redirect ?: __u('index/index'));
            }
            $bg = hook_one('bgHook')?hook_one('bgHook'):'/static/backend/images/admin-bg.jpg';
            $view = ['bg'=>$bg, 'redirect' => $redirect];
            return view('',$view);
        } else {
            $post  = $this->request->post() ;
            $username = $this->request->post('username', '', ['strip_tags','trim','htmlspecialchars']);
            $password = $this->request->post('password', '',['strip_tags','trim','htmlspecialchars']);
            $rememberMe = $this->request->post('rememberMe');
            $redirect = $this->normalizeRedirect((string) $this->request->post('redirect', ''));
            $rule = [
                "username|用户名" => 'require',
                "password|密码" => 'require',
            ];
            if(config('captcha.check')){
                $rule["captcha|验证码"] = 'require|captcha';
            }
            $this->validate($post, $rule);
            try {
                $auth = AuthService::instance();
                $auth->checkLogin($username, $password, $rememberMe);
            } catch (Exception $e) {
                $this->error(lang('Login Failed')."：{$e->getMessage()}");
            }
            $this->success(lang('Login Success').'...', $redirect ?: __u('/index/index'));
        }
    }

    protected function normalizeRedirect(string $redirect): string
    {
        if ($redirect === '') {
            return '';
        }
        $parts = parse_url($redirect);
        if ($parts === false) {
            return '';
        }
        if (!empty($parts['host'])) {
            $currentHost = (string) $this->request->host(true);
            if (strcasecmp((string) $parts['host'], $currentHost) !== 0) {
                return '';
            }
        }
        $path = (string) ($parts['path'] ?? '');
        $baseFile = (string) $this->request->baseFile();
        $baseDir = rtrim(str_replace('\\', '/', dirname($baseFile)), '/');
        $allowedPrefixes = array_filter([
            $baseFile,
            $baseDir ? $baseDir . '/' : '',
            '/backend/',
        ]);
        foreach ($allowedPrefixes as $prefix) {
            if ($prefix !== '' && str_starts_with($path, $prefix)) {
                return $redirect;
            }
        }
        return '';
    }
    public function verify()
    {
        return parent::verify(); // TODO: Change the autogenerated stub
    }

}
